first_app_session/config/routes.rb
Rails.application.routes.draw do

  get 'users/checkuser' => 'users#check_user'

  devise_for :users,  controllers: { registrations: "mydevisecontroller/registrations" }
  resources :likes
  resources :microposts
  resources :comments

  resources :users do
    collection do
      post 'signin'
    end
  end

  post 'logout' => 'users#signout'
  get 'users/:id/showposts' => 'users#show_user_posts', :as => :users_showposts

  get 'users/:id/microposts' => 'microposts#showposts_byuser_id'

  get 'users/:id/microposts/:micropost_id/comments' => 'comments#get_comments_for_micropost'
  root :to => 'microposts#index'

  

end

first_app_session/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :microposts
  has_many :comments
  has_many :likes
  #validates :name, presence: true, length: { minimum: 6, maximum: 8 }
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  def signin

  end
end

first_app_session/app/controllers/users_controller.rb
require 'byebug'
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! ,only: [:index]
  respond_to :json

  # GET /users
  # GET /users.json
  def index
    #it returns all te users
    @users = User.all
    render :json => @users

  end

  # GET /users/1
  # GET /users/1.json
  #before show, set_user function is called
  def show
    render :json => @user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end


  def check_user
    if current_user
      @user = User.find(current_user)
      render json: {response: "success", user_data: @user}, status: :ok
    else
      render :json => {response:"failure"}
    end
  end


  def show_user_posts
    @microposts = Micropost.where(:user_id => current_user.id)
    @comments = []
    #byebug
    @microposts.each { |micropost| @comments.push(micropost.comments)}
    render :json => { :microposts => @microposts, :comments => @comments }
    #render :json => @comments
  end

  # POST /users
  # POST /users.json
  def create
    byebug

    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def signin
    @user = User.find_by(email: params[:email])
    if !@user.nil? && @user.valid_password?(params[:password])
      sign_in(:user, @user)
      #debugger
      render json: {response: "success", user_data: @user}, status: :ok
    else
      render json: {response: "failure"}, status: :ok
    end
  end


  def signout
    #byebug
    @user = User.find(current_user.id)
    if @user
      sign_out(@user)
      render :json => {response: "signout_success"}
    else
      render :json => {response: "signout_failure"}
    end
  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

first_app_session/app/helpers/users_helper.rb
module UsersHelper
end

first_app_session/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

first_app_session/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

first_app_session/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div align=right> <%= link_to 'Sign out', destroy_user_session_path, :class => "btn btn-success", method: :delete%></div>

<h1>Listing Users</h1>

<table class="table table-striped">
  <thead>
    <tr align="left">
      <th>email</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>

        
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Post by you', users_showposts_path(current_user.id), :controller => "users", :action => "show_user_posts" %>
<% if false %>
    <%= link_to 'New User', new_user_path %>
<% end %>

first_app_session/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

first_app_session/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="text-­warning">
	<h2>
	  <code>email:</code>
	  <mark><%= @user.email %></mark>
	</h2>
</div>

<%= link_to 'Edit', edit_user_path(@user), :class=> "btn btn-lg" %> |
<%= link_to 'Back', users_path, :class=> "btn btn-lg" %>

first_app_session/app/views/users/show_user_posts.html.erb
<div align=right> <%= link_to 'Sign out', destroy_user_session_path, :class => "btn btn-success", method: :delete%></div>
<h1>Listing Microposts</h1>

<table class="table">
  <thead>
    <tr align="left">
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
      </tr>
    <% end %>
  </tbody>
</table>