first_app_session/config/routes.rb
Rails.application.routes.draw do

  get 'users/checkuser' => 'users#check_user'

  devise_for :users,  controllers: { registrations: "mydevisecontroller/registrations" }
  resources :likes
  resources :microposts
  resources :comments

  resources :users do
    collection do
      post 'signin'
    end
  end

  post 'logout' => 'users#signout'
  get 'users/:id/showposts' => 'users#show_user_posts', :as => :users_showposts

  get 'users/:id/microposts' => 'microposts#showposts_byuser_id'

  get 'users/:id/microposts/:micropost_id/comments' => 'comments#get_comments_for_micropost'
  root :to => 'microposts#index'

  

end

first_app_session/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :micropost
  belongs_to :user
  validates :body, presence:true, :length => { :maximum => 140 }
  validates :user_id, presence: true
end

first_app_session/app/controllers/comments_controller.rb
require 'byebug'
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :get_comments_for_post, only: [:get_comments_for_post]
  # GET /comments
  # GET /comments.json
  def index
    @micropost = Micropost.find(params[:micropost_id])
    @comments = @micropost.comments.all
    render :json => @comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new(:micropost_id => params[:micropost_id])
  end



  def get_comments_for_post
    render :json => @comments
  end



  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(:micropost_id => params[:comment][:micropost], :user_id => current_user.id, \
    :body =>  params[:comment][:body])

    #@micropost = Micropost.find(params[:micropost_id])

    #respond_to do |format|
      if @comment.save
        render :json => {:response => "comment saved succcessfully"}
        #format.html { redirect_to @micropost, notice: 'Comment was successfully created.' }
        #format.json { render :show, status: :created, location: @comment }
      else
        #format.html { render :new }
        #format.json { render json: @comment.errors, status: :unprocessable_entity }
      #end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @micropost = Micropost.find(params[:micropost_id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @micropost, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @micropost = Micropost.find(params[:micropost_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @micropost, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :micropost_id)
    end
end

first_app_session/app/helpers/comments_helper.rb
module CommentsHelper
end

first_app_session/app/views/comments/_form.html.erb
<%= form_for([@comment.micropost, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
 
  <div class="field">
    <%= f.label :micropost_id %><br>
    <%= f.number_field :micropost_id %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

first_app_session/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', micropost_comment_path %> |
<%= link_to 'Back', micropost_comments_path %>

first_app_session/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table class="table">
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.micropost_id %></td>
        <td><%= link_to 'Show', [comment.micropost, comment] %></td>
        <td><%= link_to 'Edit', edit_micropost_comment_path(comment.micropost, comment) %></td>
        <td><%= link_to 'Destroy', [comment.micropost, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_micropost_comment_path %>

first_app_session/app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render 'form' %>

<%= link_to 'Back', micropost_comments_path %>

first_app_session/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.micropost_id %>
</p>

<%= link_to 'Edit', edit_micropost_comment_path(@comment.micropost, @comment) %> |
<%= link_to 'Back', micropost_comments_path %>