first_app_session/config/routes.rb
Rails.application.routes.draw do

  get 'users/checkuser' => 'users#check_user'

  devise_for :users,  controllers: { registrations: "mydevisecontroller/registrations" }
  resources :likes
  resources :microposts
  resources :comments

  resources :users do
    collection do
      post 'signin'
    end
  end

  post 'logout' => 'users#signout'
  get 'users/:id/showposts' => 'users#show_user_posts', :as => :users_showposts

  get 'users/:id/microposts' => 'microposts#showposts_byuser_id'

  get 'users/:id/microposts/:micropost_id/comments' => 'comments#get_comments_for_micropost'
  root :to => 'microposts#index'

  

end

first_app_session/app/models/micropost.rb
class Micropost < ActiveRecord::Base
  #attr_accessible :content, :user_id
  belongs_to :user
  has_many :likes
  has_many :comments
  validates :content, presence: true, :length => { :maximum => 140 }
  validates :user_id, presence: true

  def likescount
    self.likes.count
  end
end

first_app_session/app/controllers/microposts_controller.rb
require 'byebug'
class MicropostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]
  #respond_to :json
  # GET /microposts
  # GET /microposts.json
  def index
    #debugger
    @microposts = Micropost.where(:user_id => params[:user_id])
    #@likes_count = []
    #byebug
    #@microposts.each { |post| @likes_count.push(post.likes.count)}

    render :json => @microposts
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    #byebug
    @comments = Micropost.all.find(params[:id]).comments.paginate(:page => params[:page])

    #@micropost is defined by set_params method which is before action method
    render :json => @micropost
  end


  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end



  def showposts_byuser_id
    @microposts = Micropost.where(:user_id => params[:id])
    render :json => @microposts
  end
  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create

    @micropost = Micropost.new(:content => params[:micropost][:content], :user_id => current_user.id)

    #respond_to do |format|
      if @micropost.save
        #format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        #format.json { render :show, status: :created, location: @micropost }
        render :json => {response: "success"}
      else
        #format.html { render :new }
        #format.json { render json: @micropost.errors, status: :unprocessable_entity }
        render :json => {response: "failure"}
      end
    #end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    #respond_to do |format|
     # format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      #format.json { head :no_content }
    #end
    render :json => { :status => "post deleted"}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

first_app_session/app/helpers/microposts_helper.rb
module MicropostsHelper
end

first_app_session/app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

first_app_session/app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

first_app_session/app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<div align=right> <%= link_to 'Sign out', destroy_user_session_path, :class => "btn btn-success", method: :delete%></div>
<h1>Listing Microposts</h1>

<table class="table">
  <thead>
    <tr align="left">
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= will_paginate @microposts %>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>

        <% if micropost.likes.where(:user_id => current_user.id).count == 1 %> 
          <td><%= link_to 'Unlike', like_path(micropost.likes.where(:user_id => current_user.id).first.id,:destroy => true), method: :delete,  data: { confirm: 'Are you sure?' }  %></td>
        <% else %>
          <td><%= link_to 'Like', likes_path(:micropost_id => micropost), method: :post %></td>
        <% end %>


        <td><%= micropost.likes.count %></td>
      <% if micropost.user_id == current_user.id %>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= current_user.id %>
<br>

<%= link_to 'New Micropost', new_micropost_path %>

first_app_session/app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

first_app_session/app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>


<h2>Comments</h2>
<%= will_paginate @comments %>
<% @comments.each do |comment| %>
    <p>
      <strong>User:</strong>
      <%= comment.user_id %>
    </p>

    <p>
      <strong>Comment:</strong>
      <%= comment.body %>
    </p>
<% end %>


<h2>Add a comment:</h2>
<%= form_for([@micropost, @micropost.comments.build]) do |f| %>
    <div>
      <%= f.label :body %><br>
      <%= f.text_field :body %>
    </div>
  
    <div class="field">
      <%= f.label :micropost_id %><br>
      <%= f.number_field :micropost_id %>
    </div>
  
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>


<%= link_to 'Edit', edit_micropost_path %> |
<%= link_to 'Back', microposts_path %>